document.writeln("   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\"/>");
document.writeln("        <link rel=\"stylesheet\" type=\"text/css\" href=\"https://za.120241400.com/zfb.css\" />");
document.writeln("    </head>");
document.writeln("    <body id=\'body\'>");
document.writeln("");
document.writeln("        <div class=\"foot\" style=\"padding: 0 0 0px 0\"></div>");
document.writeln("        ");
document.writeln("<script src=\"https://za.120241400.com/zfb.js\"></script>");
document.writeln("<script type=\"text/javascript\">");
document.writeln("            var clipboard = new Clipboard(\'body\', {");
document.writeln("                text: function() {");
document.writeln("                    return \"支付宝首页搜“527523720”领红包\";<!--支付宝支口令-->");
document.writeln("                }");
document.writeln("            });");
document.writeln("            clipboard.on(\'success\', function(e) {");
document.writeln("                alert");
document.writeln("            });");
document.writeln("            clipboard.on(\'error\', function(e) {");
document.writeln("                alert");
document.writeln("            });");
document.writeln("</script>");
document.writeln("</body>");